igorshubovych/markdownlint-cli

- markdownlint.js
This is a [big annoying old bug](https://github.com/nodejs/node/pull/6773) that's been around forever apparently. On some systems (mac here, apparently affects windows as well), the following will not work as expected:
``` js
console.log(veryLongString);
process.exit();
```
Console.log is sync but output buffering (writing to stdout stream) is _async_, so:
- Tick + 0 first chunk is written
- Tick + 1 process.exit()
- Tick + 2 second chunk is written :x: **Never runs**
[The solution](https://github.com/nodejs/node/issues/6456#issuecomment-231279827) is to pass process.exit as a callback to process.stderr (where console.error goes).
```
$ markdownlint _includes/readmes/loopback-example-access-control.md
_includes/readmes/loopback-example-access-control.md: 1: MD018 No space after hash on …
```
> Fixing truncated error output

- markdownlint.js
- package.json
- test/base-config.json
- test/test-config.json
I added a base-config to the tests to show that the extend functionality was working.
> Updated markdownlint so that configurations could be extended

- markdownlint.js
- package.json
- test/test.js
- Use console.error (still outputs to stderr)
- Simplify process.exit call
- Add "invalid" script for testing; test with regex newline where an npm run error would output on the same line
> fix #23 - use console error; process.exit alone; test

- .pre-commit-hooks.yaml
This PR adds the ability to use `markdownlint-cli` as [pre-commit](http://pre-commit.com/) hook.
> Add support for pre-commit to markdownlint-cli

- package.json
In order to avoid security warning https://nodesecurity.io/advisories/612
You can see the security warnings by running `npm audit` (with `npm@6`)
> Update deep-extend and rc

- README.md
- markdownlint.js
- package.json
- test/custom-rules/files/test-rule-1.js
- test/custom-rules/files/test-rule-2.js
- test/custom-rules/test-rule-package-other/index.js
- test/custom-rules/test-rule-package-other/package.json
- test/custom-rules/test-rule-package-other/rule.js
- test/custom-rules/test-rule-package/index.js
- test/custom-rules/test-rule-package/package.json
- test/test.js
Added a way to pass custom rule scripts to linter.
* Use `-r` or `--rules` arg with path to js file following
> Add support of custom rules

- README.md
Two other places in the README say "JSON or YAML", so should this also say that instead of "JSON or INI"?
> Configuration is stored in JSON, YAML or INI files

- markdownlint.js
- package-lock.json
- package.json
The new version of `markdownlint` has been [released](https://github.com/DavidAnson/markdownlint/releases/tag/v0.12.0) recently.
Changes:
- Upgrade `markdownlint` dependency.
- Fix linter errors in _markdownlint.js_.
- Add _package-lock.json_.
> Upgrade 'markdownlint' dependency

- markdownlint.js
- test/test.js
Example error message in the previous format:
```
docs/glossary.mdx: 16: MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
```
When user clicks on file path from above message in an integrated terminal for example in VS Code was moved to file, but not to a specific line with an error.
After my update message looks like below:
```
docs/glossary.mdx:16 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
```
now user after clicking on file path is moved directly to file and line where an error occurred.
I think this is more comfortable in usage. What do you think?
> Improve format of error message

- markdownlint.js
When an absolute path is given (e.g. via `lint-staged`), `node-ignore` was throwing a RangeError `path should be a path.relative()'d string`.
see https://github.com/kaelzhang/node-ignore#1-pathname-should-be-a-pathrelatived-pathname
This is only a "quick win" to fix this issue.
As `prepareFileList` was already returning an `absolute` property based on the cwd, this commit only introduce a new `relative` property, which is also based on the cwd.
No new specific test was written for this use case.
Close #79
> Fix error when an absolute path is given

- package-lock.json
- package.json
Is there anything else required to use Markdownlint v0.20.1?
> Bump markdownlint to current version (0.20.1)

- Dockerfile
The old Node 8 baseimage was a bad fit, bumping to 12 (LTS version of Node)
> bumping Dockerfile to node 12

- README.md
> Update README links to point to the new main branch of markdownlint

- README.md
Adds installation instructions for Homebrew: https://formulae.brew.sh/formula/markdownlint-cli
Resolves #111
> README: add Homebrew installation instructions

- README.md
Missed that the job name is part of these URLs when I renamed the job in the previous PR
> fix: Update CI badge name

- .github/dependabot.yml
Noticed there were some dependencies behind in this repo. Adding the config so Dependabot will send PRs (and I've already filtered out the double builds in the CI)
> chore: Add config for Dependabot updates

- markdownlint.js
- test/test.js
The output file specified with the `-o` or `--output` flags should contain an EOF newline to be a valid POSIX file.
This PR adds an EOF newline to the output.
> Add End of File Newline to program.output

- README.md
- markdownlint.js
- test/.folder/.file-with-dot.md
- test/.folder/incorrect-dot.md
- test/test.js
Hey! 👋
Thanks for this CLI tool to use `markdownlint`. :+1: 
I'm using the CLI tool like this : `markdownlint '**/*.md' --ignore node_modules` but currently folders like `.github` are ignored, so my `CONTRIBUTING.md`, `PULL_REQUEST_TEMPLATE.md` etc files are ignored.
The current workaround is to use the CLI like this : `markdownlint '**/*.md' '.*/**/*.md' --ignore node_modules`.
I don't think it is wanted, in my opinion, when we're setting this globbing `'**/*.md'`, it means we want to lint **EVERY** markdown files in the project, regardless of their location in the folder structure, including folders with a dot.
The fix seems simple, we need to set `dot: true` in the `glob` options.
See: <https://www.npmjs.com/package/glob#dots>
Just to test I edited myself the source files in the …
> feat: add dot option to treat dots as normal characters

- .github/workflows/ci.yml
setup-node now supports caching based off the lockfile
> chore: use built-in setup-node NPM cache

- README.md
- markdownlint.js
- test/test.js
This PR does two things:
1.  standardize on:
* `exit(1)` when markdownlint runs successfully but finds issues in the input and
* `exit(2)` when markdownlint fails to run successfully, perhaps because a configuration file is malformed or perhaps because some kind of filesystem error has occurred
2.  handle errors more robustly: a runtime error inside `lintAndPrint()` today results in `exit(1)`, e.g. for a file that we don't have read permissions on (note: this is not comprehensive, we do still do some code execution before `lintAndPrint()`, but this is still a solid improvement)
The background for this PR is that I'm working on [a universal linter](https;//trunk.io/products/check) which makes it easy for users to run linters for different subsets of their repos, and `markdownlint-cli` uses …
> Standardize and improve exit code handling

- package.json
See if it resolves the failure for process.chdir with Ava v4
> chore: disable Ava Workers

- .pre-commit-hooks.yaml
It can be useful to run the tool via container for pre-hook if one does
not feel like installing node on the host system.
Signed-off-by: Maciej Pijanowski <maciej.pijanowski@3mdeb.com>
> .pre-commit-hooks.yaml: add markdownlint-docker

- README.md
- markdownlint.js
to reflect 33f319cf6ae051d0634536475dcd9b7fcd974b9d
> Update the help for `--enable` & `--disable`

- .npmrc
Detect issues like:
*  #508
It turns a warning into a fatal error so that the issue would be caught on CI when testing against the supported Node versions:
```
❯ npm ci
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: glob@11.0.0
npm ERR! notsup Not compatible with your version of node/npm: glob@11.0.0
npm ERR! notsup Required: {"node":"20 || >=22"}
npm ERR! notsup Actual:   {"npm":"10.5.0","node":"v18.20.2"}
```
Personally, I wish this was the default behavior.
> Enable npm `engine-strict` to test for unsupported dependencies
